### ISSUE TITLE
Upstream doesnt seem to work

### ISSUE THREAD

**Issue by Doridian** [Doridian/klipper#3]
See https://github.com/Doridian/klipper/tree/python3-doesntwork branch. Somehow this just hangs connecting to my printer.
Sometimes I get an exit code 255 loop.
Will need to investigate further to see if this is upstream or py3 issue.

**Comment by Piezoid** [comment]
That's a weird behavior, running this on my printer produced a traceback in the logs. 
Solved with:
```diff
diff --git a/klippy/webhooks.py b/klippy/webhooks.py
index a4c5f657..886631bc 100644
--- a/klippy/webhooks.py
+++ b/klippy/webhooks.py
@@ -237,7 +237,7 @@ class ClientConnection:
         self.send(result)
 
     def send(self, data):
-        self.send_buffer += json.dumps(data, separators=(',', ':')) + b"\x03"
+        self.send_buffer += json.dumps(data, separators=(',', ':')).encode() + b"\x03"
         if not self.is_sending_data:
             self.is_sending_data = True
             self.reactor.register_callback(self._do_send)
```
(69d9497df325b0ea7ef71824f7106ae09fcbcdbb conflicting with 075cc78d727f56c1469f2550563969a64d421780)

**Comment by Doridian** [comment]
Thanks a lot for the fix! Yeah I don't know why it wouldn't give me an exception, never seen that before.
